name: Elixir CI

on: push

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '24.1.2'
          elixir-version: '1.13.4'
          
      - run: mix local.hex --force
      - run: mix local.rebar --force
        
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
          
      - run: |
          echo 'export CLIENT_TOKEN="test_client_token"' >> $GITHUB_ENV
          echo 'export MIX_ENV="test"' >> $GITHUB_ENV
        name: setup environment variables
        
      - name: Install dependencies
        run: mix deps.get
      - run: mix format --check-formatted --dry-run
      - run: MIX_ENV=test mix compile --force --warnings-as-errors

      - name: Install nginx
        run: |
          sudo apt update
          sudo apt install nginx
          sudo mv ./priv/grpc_gateway.conf /etc/nginx/conf.d
          sudo systemctl restart nginx

      - run: MIX_ENV=test mix test

      - name: Print log
        run: |
          cat /var/log/nginx/access.log
          cat /var/log/nginx/error.log
          cat /var/log/nginx/grpc_log.json
